Repository Attica-org/athens-backend, pull requests merged in 2024-10, with the labels that each got.

#192 chore: 배포 스크립트 수정
  docker-compose.blue.yml
  docker-compose.green.yml
  docker-compose.yml
Labels: chore

#194 chore: 배포 스크립트 수정
  docker-compose.blue.yml
  docker-compose.green.yml
  docker-compose.yml
Labels: chore

#196 chore: 배포스크립트 수정
  deploy-prod.sh
  docker-compose.blue.yml
  docker-compose.green.yml
  docker-compose.yml
Labels: chore

#198 chore: 스크립트 수정
  docker-compose.yml
Labels: chore

#205 fix: 컨테이너 중복 생성 문제 해결
  deploy-prod.sh
  docker-compose.blue.yml
  docker-compose.green.yml
  docker-compose.yml
Labels: chore

#210 chore: redis 컨테이너도 함께 내리기
  deploy-prod.sh
Labels: chore

#211 Dev->Main
  deploy-prod.sh
Labels: chore

#212 chore: 배포 스크립트 수정
  deploy-prod.sh
Labels: chore

#216 chore: 배포 스크립트 수정 (무중단 배포)
  .github/workflows/backend-cd.yaml
  deploy-prod.sh
Labels: chore

#218 fix: 이전 버전 컨테이너만 종료되도록 수정
  deploy-prod.sh
Labels: chore

#219 Dev->Main
  deploy-prod.sh
Labels: chore

#220 fix: 도커 명령어 수정
  deploy-prod.sh
Labels: chore

#222 fix: 도커 명령어 수정
  deploy-prod.sh
Labels: chore

#223 Dev->Main
  deploy-prod.sh
Labels: chore

#224 fix: 컨테이너 제거되지 않는 문제 해결
  deploy-prod.sh
Labels: chore

#204 클라이언트 요구사항 반영
  src/main/java/com/attica/athens/domain/agora/api/AgoraAuthController.java
  src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
  src/main/java/com/attica/athens/domain/agora/dto/response/AgoraParticipateResponse.java
  src/main/java/com/attica/athens/domain/agora/dto/response/UpdateThumbnailResponse.java
  src/main/java/com/attica/athens/domain/agora/exception/ImageUpdateAccessDeniedException.java
Labels: ✅ Status: Done, refactor

#226 fix: 에러 해결
  src/main/java/com/attica/athens/domain/chat/application/ChatCommandService.java
  src/main/java/com/attica/athens/domain/member/api/MemberOpenController.java
  src/main/java/com/attica/athens/global/auth/jwt/JwtUtils.java
  src/test/java/com/attica/athens/domain/chat/ChatWebSocketApiIntegrationTest.java
Labels: 🐛 Type: Bug

#229 #190 프론트엔드 요구사항 리팩토링
  src/main/java/com/attica/athens/domain/agora/api/AgoraAuthController.java
  src/main/java/com/attica/athens/domain/agora/api/AgoraOpenController.java
  src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
  src/main/java/com/attica/athens/domain/agora/dao/AgoraQueryRepositoryImpl.java
  src/main/java/com/attica/athens/domain/agora/dao/AgoraRepository.java
  src/main/java/com/attica/athens/domain/agora/dto/response/AgoraTitleResponse.java
  src/main/java/com/attica/athens/domain/agoraMember/application/AgoraMemberService.java
  src/main/java/com/attica/athens/domain/agoraMember/dao/AgoraMemberRepository.java
  src/main/java/com/attica/athens/domain/agoraMember/exception/NotFoundAgoraMemberException.java
  src/main/java/com/attica/athens/domain/chat/api/ChatAuthController.java
  src/main/java/com/attica/athens/domain/member/dao/MemberRepository.java
  src/main/java/com/attica/athens/domain/member/exception/NotFoundMemberException.java
  src/main/java/com/attica/athens/global/auth/exception/SessionReconnectException.java
  src/main/java/com/attica/athens/global/config/WebSocketConfig.java
  src/main/java/com/attica/athens/global/decorator/HeartBeatManager.java
  src/main/java/com/attica/athens/global/handler/HeartBeatHandler.java
  src/main/java/com/attica/athens/global/handler/WebSocketEventHandler.java
  src/main/java/com/attica/athens/global/interceptor/JwtChannelInterceptor.java
  src/test/java/com/attica/athens/config/TestRedisConfig.java
  src/test/java/com/attica/athens/domain/agora/AgoraAuthApiIntegrationTest.java
  src/test/java/com/attica/athens/global/WebSocket/HeartBeat/HeartBeatIntegrationTest.java
  src/test/java/com/attica/athens/global/WebSocket/HeartBeat/HeartBeatInterceptorTest.java
  src/test/java/com/attica/athens/global/WebSocket/HeartBeat/HeartBeatManagerTest.java
  src/test/java/com/attica/athens/support/IntegrationTestSupport.java
Labels: 🚩 Priority: High, 🐛 Type: Bug, ✨ Type: Enhancement, feature, refactor

#231 [#190]refactor: agoraTitleResponse 응답값 color 추가
  src/main/java/com/attica/athens/domain/agora/dao/AgoraQueryRepositoryImpl.java
  src/main/java/com/attica/athens/domain/agora/dto/response/AgoraTitleResponse.java
  src/main/java/com/attica/athens/domain/agoraMember/application/AgoraMemberService.java
  src/main/java/com/attica/athens/global/decorator/HeartBeatManager.java
  src/main/java/com/attica/athens/global/handler/HeartBeatHandler.java
  src/main/java/com/attica/athens/global/handler/WebSocketEventHandler.java
Labels: refactor

#232 Dev -> Main
  src/main/java/com/attica/athens/domain/agora/dao/AgoraQueryRepositoryImpl.java
  src/main/java/com/attica/athens/domain/agora/dto/response/AgoraTitleResponse.java
  src/main/java/com/attica/athens/domain/agoraMember/application/AgoraMemberService.java
  src/main/java/com/attica/athens/global/decorator/HeartBeatManager.java
  src/main/java/com/attica/athens/global/handler/HeartBeatHandler.java
  src/main/java/com/attica/athens/global/handler/WebSocketEventHandler.java
Labels: refactor

#236 WebSocketEventHandler 상수 수정
  src/main/java/com/attica/athens/global/handler/WebSocketEventHandler.java
Labels: refactor
