Repository Attica-org/athens-backend, pull requests merged in 2024-06, with the labels that each got.

#62 채팅 기능 구현 및 토론 종료하기 API 구현
  build.gradle
  src/main/java/com/attica/athens/domain/agora/api/AgoraAuthController.java
  src/main/java/com/attica/athens/domain/agora/api/AgoraOpenController.java
  src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
  src/main/java/com/attica/athens/domain/agora/domain/Agora.java
  src/main/java/com/attica/athens/domain/agora/dto/response/EndVoteAgoraResponse.java
  src/main/java/com/attica/athens/domain/agora/dto/response/StartAgoraResponse.java
  src/main/java/com/attica/athens/domain/agora/exception/InvalidAgoraStatusChangeException.java
  src/main/java/com/attica/athens/domain/agora/exception/InvalidAgoraStatusException.java
  src/main/java/com/attica/athens/domain/agora/exception/NotFoundAgoraException.java
  src/main/java/com/attica/athens/domain/agoraUser/dao/AgoraUserRepository.java
  src/main/java/com/attica/athens/domain/agoraUser/domain/AgoraUser.java
  src/main/java/com/attica/athens/domain/agoraUser/exception/AlreadyVotedException.java
  src/main/java/com/attica/athens/domain/agoraUser/exception/NotFoundAgoraUserException.java
  src/main/java/com/attica/athens/domain/chat/api/ChatAuthController.java
  src/main/java/com/attica/athens/domain/chat/application/ChatCommandService.java
  src/main/java/com/attica/athens/domain/chat/application/ChatQueryService.java
  src/main/java/com/attica/athens/domain/chat/dto/request/SendChatRequest.java
  src/main/java/com/attica/athens/domain/chat/dto/response/ErrorResponse.java
  src/main/java/com/attica/athens/domain/chat/dto/response/GetChatParticipants.java
  src/main/java/com/attica/athens/domain/chat/dto/response/GetChatResponse.java
  src/main/java/com/attica/athens/domain/chat/dto/response/SendChatResponse.java
  src/main/java/com/attica/athens/domain/chat/dto/response/SendMetaResponse.java
  src/main/java/com/attica/athens/domain/common/ApiUtil.java
  src/main/java/com/attica/athens/global/auth/config/SecurityConfig.java
  src/main/java/com/attica/athens/global/auth/exception/JwtException.java
  src/main/java/com/attica/athens/global/auth/exception/JwtExpiredException.java
  src/main/java/com/attica/athens/global/auth/exception/JwtIllegalArgumentException.java
  src/main/java/com/attica/athens/global/auth/exception/JwtSignatureException.java
  src/main/java/com/attica/athens/global/auth/exception/JwtUnsupportedJwtException.java
  src/main/java/com/attica/athens/global/config/WebSocketConfig.java
  src/main/java/com/attica/athens/global/config/WebSocketSecurityConfig.java
  src/main/java/com/attica/athens/global/handler/WebSocketExceptionHandler.java
  src/main/java/com/attica/athens/global/interceptor/JwtChannelInterceptor.java
Labels: 🚩 Priority: High, 🐛 Type: Bug, ✨ Type: Enhancement, feature

#65 Dev -> Main
  .github/workflows/backend-cd.yaml
  .github/workflows/backend-ci.yaml
  build.gradle
  docker-compose.yml
  src/main/java/com/attica/athens/domain/agora/api/AgoraAuthController.java
  src/main/java/com/attica/athens/domain/agora/api/AgoraOpenController.java
  src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
  src/main/java/com/attica/athens/domain/agora/domain/Agora.java
  src/main/java/com/attica/athens/domain/agora/dto/response/EndVoteAgoraResponse.java
  src/main/java/com/attica/athens/domain/agora/dto/response/StartAgoraResponse.java
  src/main/java/com/attica/athens/domain/agora/exception/InvalidAgoraStatusChangeException.java
  src/main/java/com/attica/athens/domain/agora/exception/InvalidAgoraStatusException.java
  src/main/java/com/attica/athens/domain/agora/exception/NotFoundAgoraException.java
  src/main/java/com/attica/athens/domain/agoraUser/dao/AgoraUserRepository.java
  src/main/java/com/attica/athens/domain/agoraUser/domain/AgoraUser.java
  src/main/java/com/attica/athens/domain/agoraUser/exception/AlreadyVotedException.java
  src/main/java/com/attica/athens/domain/agoraUser/exception/NotFoundAgoraUserException.java
  src/main/java/com/attica/athens/domain/chat/api/ChatAuthController.java
  src/main/java/com/attica/athens/domain/chat/application/ChatCommandService.java
  src/main/java/com/attica/athens/domain/chat/application/ChatQueryService.java
  src/main/java/com/attica/athens/domain/chat/dto/request/SendChatRequest.java
  src/main/java/com/attica/athens/domain/chat/dto/response/ErrorResponse.java
  src/main/java/com/attica/athens/domain/chat/dto/response/GetChatParticipants.java
  src/main/java/com/attica/athens/domain/chat/dto/response/GetChatResponse.java
  src/main/java/com/attica/athens/domain/chat/dto/response/SendChatResponse.java
  src/main/java/com/attica/athens/domain/chat/dto/response/SendMetaResponse.java
  src/main/java/com/attica/athens/domain/common/ApiUtil.java
  src/main/java/com/attica/athens/global/auth/application/AuthService.java
  src/main/java/com/attica/athens/global/auth/config/SecurityConfig.java
  src/main/java/com/attica/athens/global/auth/dao/RefreshTokenRepository.java
  src/main/java/com/attica/athens/global/auth/exception/JwtException.java
  src/main/java/com/attica/athens/global/auth/exception/JwtExpiredException.java
  src/main/java/com/attica/athens/global/auth/exception/JwtIllegalArgumentException.java
  src/main/java/com/attica/athens/global/auth/exception/JwtSignatureException.java
  src/main/java/com/attica/athens/global/auth/exception/JwtUnsupportedJwtException.java
  src/main/java/com/attica/athens/global/auth/filter/CustomLogoutFilter.java
  src/main/java/com/attica/athens/global/auth/filter/LoginFilter.java
  src/main/java/com/attica/athens/global/config/WebSocketConfig.java
  src/main/java/com/attica/athens/global/config/WebSocketSecurityConfig.java
  src/main/java/com/attica/athens/global/handler/WebSocketExceptionHandler.java
  src/main/java/com/attica/athens/global/interceptor/JwtChannelInterceptor.java
Labels: feature

#70 에러 수정 및 리팩토링
  src/main/java/com/attica/athens/domain/agora/api/AgoraAuthController.java
  src/main/java/com/attica/athens/domain/agora/api/AgoraOpenController.java
  src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
  src/main/java/com/attica/athens/domain/agora/domain/Agora.java
  src/main/java/com/attica/athens/domain/agora/dto/response/AgoraParticipateResponse.java
  src/main/java/com/attica/athens/domain/agoraUser/domain/AgoraUser.java
  src/main/java/com/attica/athens/domain/common/advice/GlobalExceptionHandler.java
  src/main/java/com/attica/athens/global/auth/application/AuthService.java
  src/main/java/com/attica/athens/global/auth/config/SecurityConfig.java
  src/main/java/com/attica/athens/global/auth/filter/CustomLogoutFilter.java
  src/main/java/com/attica/athens/global/auth/filter/JwtFilter.java
  src/main/java/com/attica/athens/global/auth/filter/LoginFilter.java
  src/main/java/com/attica/athens/global/auth/jwt/JwtUtils.java
  src/main/java/com/attica/athens/global/config/JpaConfig.java
  src/main/resources/application-prod.yml
Labels: 🚩 Priority: High, feature, chore, refactor

#71 Dev -> Main
  src/main/java/com/attica/athens/domain/agora/api/AgoraAuthController.java
  src/main/java/com/attica/athens/domain/agora/api/AgoraOpenController.java
  src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
  src/main/java/com/attica/athens/domain/agora/domain/Agora.java
  src/main/java/com/attica/athens/domain/agora/dto/response/AgoraParticipateResponse.java
  src/main/java/com/attica/athens/domain/agoraUser/domain/AgoraUser.java
  src/main/java/com/attica/athens/domain/common/advice/GlobalExceptionHandler.java
  src/main/java/com/attica/athens/global/auth/application/AuthService.java
  src/main/java/com/attica/athens/global/auth/config/SecurityConfig.java
  src/main/java/com/attica/athens/global/auth/filter/CustomLogoutFilter.java
  src/main/java/com/attica/athens/global/auth/filter/JwtFilter.java
  src/main/java/com/attica/athens/global/auth/filter/LoginFilter.java
  src/main/java/com/attica/athens/global/auth/jwt/JwtUtils.java
  src/main/java/com/attica/athens/global/config/JpaConfig.java
  src/main/resources/application-prod.yml
Labels: 🚩 Priority: High, feature, chore, docs

#75 Dev -> Main
  src/main/java/com/attica/athens/global/config/WebSocketConfig.java
Labels: 🚩 Priority: High

#76 chore: file:// 허용하도록 수정
  src/main/resources/application-prod.yml
Labels: 🚩 Priority: High

#77 Dev -> Main
  src/main/resources/application-prod.yml
Labels: chore

#73 투표하기 및 투표 결과 API / 아고라 title 단건 조회 및 아고라 ID 리스트 조회
  build.gradle
  src/main/java/com/attica/athens/domain/agora/api/AgoraOpenController.java
  src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
  src/main/java/com/attica/athens/domain/agora/dao/AgoraQueryRepository.java
  src/main/java/com/attica/athens/domain/agora/dao/AgoraQueryRepositoryImpl.java
  src/main/java/com/attica/athens/domain/agora/domain/Agora.java
  src/main/java/com/attica/athens/domain/agora/dto/request/AgoraParticipateRequest.java
  src/main/java/com/attica/athens/domain/agora/dto/response/AgoraIdResponse.java
  src/main/java/com/attica/athens/domain/agora/dto/response/AgoraTitleResponse.java
  src/main/java/com/attica/athens/domain/agora/vote/api/AgoraVoteController.java
  src/main/java/com/attica/athens/domain/agora/vote/application/AgoraVoteService.java
  src/main/java/com/attica/athens/domain/agora/vote/dao/AgoraVoteRepository.java
  src/main/java/com/attica/athens/domain/agora/vote/dao/AgoraVoteRepositoryImpl.java
  src/main/java/com/attica/athens/domain/agora/vote/dto/request/AgoraVoteRequest.java
  src/main/java/com/attica/athens/domain/agora/vote/dto/response/AgoraVoteResponse.java
  src/main/java/com/attica/athens/domain/agora/vote/dto/response/AgoraVoteResultResponse.java
  src/main/java/com/attica/athens/domain/agora/vote/exception/AlreadyOpinionVotedException.java
  src/main/java/com/attica/athens/domain/agoraUser/dao/AgoraUserRepository.java
  src/main/java/com/attica/athens/domain/agoraUser/domain/AgoraUser.java
  src/main/java/com/attica/athens/domain/agoraUser/domain/AgoraVoteType.java
  src/main/java/com/attica/athens/domain/agoraUser/exception/AlreadyEndVotedException.java
  src/main/java/com/attica/athens/domain/agoraUser/exception/NotFoundAgoraUserException.java
  src/main/java/com/attica/athens/global/auth/api/ReissueController.java
  src/main/java/com/attica/athens/global/auth/filter/LoginFilter.java
Labels: 🚩 Priority: High, 🔛 Status: In Progress, ✨ Type: Enhancement, feature

#91 hotfix: 유저 조회시 찬성, 반대 역할 유저만 보이도록 수정
  src/main/java/com/attica/athens/domain/agoraUser/dao/AgoraUserRepository.java
  src/main/java/com/attica/athens/domain/chat/application/ChatQueryService.java
Labels: feature

#92 Dev -> Main
  build.gradle
  src/main/java/com/attica/athens/domain/agora/api/AgoraAuthController.java
  src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
  src/main/java/com/attica/athens/domain/agora/dto/request/AgoraCreateRequest.java
  src/main/java/com/attica/athens/domain/agora/exception/DuplicatedNicknameException.java
  src/main/java/com/attica/athens/domain/agoraUser/dao/AgoraUserQueryRepository.java
  src/main/java/com/attica/athens/domain/agoraUser/dao/AgoraUserQueryRepositoryImpl.java
  src/main/java/com/attica/athens/domain/agoraUser/dao/AgoraUserRepository.java
  src/main/java/com/attica/athens/domain/chat/application/ChatQueryService.java
Labels: 🚩 Priority: High

#100 관찰자 권한 조정
  src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
  src/main/java/com/attica/athens/domain/agora/dto/response/EndVoteAgoraResponse.java
  src/main/java/com/attica/athens/domain/agora/exception/NotParticipateException.java
  src/main/java/com/attica/athens/domain/agora/exception/ObserverException.java
  src/main/java/com/attica/athens/domain/chat/application/ChatCommandService.java
  src/main/java/com/attica/athens/global/handler/StompErrorHandler.java
Labels: 🐛 Type: Bug, feature, refactor

#106 세션 관리 로직 구현 및 실시간 메타 정보 전송 로직 수정
  src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
  src/main/java/com/attica/athens/domain/agora/exception/FullAgoraCapacityException.java
  src/main/java/com/attica/athens/domain/agoraUser/application/AgoraUserService.java
  src/main/java/com/attica/athens/domain/agoraUser/dao/AgoraUserRepository.java
  src/main/java/com/attica/athens/domain/agoraUser/domain/AgoraUser.java
  src/main/java/com/attica/athens/domain/agoraUser/dto/response/SendMetaResponse.java
  src/main/java/com/attica/athens/domain/agoraUser/exception/NotFoundSessionException.java
  src/main/java/com/attica/athens/domain/chat/api/ChatAuthController.java
  src/main/java/com/attica/athens/domain/chat/application/ChatQueryService.java
  src/main/java/com/attica/athens/global/config/JpaConfig.java
  src/main/java/com/attica/athens/global/handler/WebSocketEventHandler.java
  src/main/java/com/attica/athens/global/handler/WebSocketExceptionHandler.java
Labels: feature

#107 Dev -> Main
  .editorconfig
  src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
  src/main/java/com/attica/athens/domain/agora/dao/AgoraQueryRepositoryImpl.java
  src/main/java/com/attica/athens/domain/agora/exception/FullAgoraCapacityException.java
  src/main/java/com/attica/athens/domain/agora/vote/dao/AgoraQueryVoteRepositoryImpl.java
  src/main/java/com/attica/athens/domain/agoraUser/application/AgoraUserService.java
  src/main/java/com/attica/athens/domain/agoraUser/dao/AgoraUserRepository.java
  src/main/java/com/attica/athens/domain/agoraUser/domain/AgoraUser.java
  src/main/java/com/attica/athens/domain/agoraUser/dto/response/SendMetaResponse.java
  src/main/java/com/attica/athens/domain/agoraUser/exception/NotFoundSessionException.java
  src/main/java/com/attica/athens/domain/chat/api/ChatAuthController.java
  src/main/java/com/attica/athens/domain/chat/application/ChatQueryService.java
  src/main/java/com/attica/athens/global/auth/application/AuthService.java
  src/main/java/com/attica/athens/global/auth/config/SecurityConfig.java
  src/main/java/com/attica/athens/global/auth/dao/RefreshTokenRepository.java
  src/main/java/com/attica/athens/global/auth/exception/InvalidRequestException.java
  src/main/java/com/attica/athens/global/auth/filter/CustomLogoutFilter.java
  src/main/java/com/attica/athens/global/auth/filter/JwtAuthenticationEntryPoint.java
  src/main/java/com/attica/athens/global/auth/filter/JwtFilter.java
  src/main/java/com/attica/athens/global/config/JpaConfig.java
  src/main/java/com/attica/athens/global/handler/WebSocketEventHandler.java
  src/main/java/com/attica/athens/global/handler/WebSocketExceptionHandler.java
Labels: feature, chore, refactor

#109 fix: 채팅 사용자 조회하기 실시간 참여자만 조회되도록 수정
  src/main/java/com/attica/athens/domain/agoraUser/dao/AgoraUserRepository.java
  src/main/java/com/attica/athens/domain/chat/application/ChatQueryService.java
Labels: refactor

#110 refactor: 메타 정보 조회 엔드포인트 수정
  src/main/java/com/attica/athens/domain/agoraUser/application/AgoraUserService.java
Labels: refactor

#112 fix: 관찰자는 종료 투표 못하도록 수정
  src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
  src/main/java/com/attica/athens/domain/agoraUser/dao/AgoraUserRepository.java
Labels: 🐛 Type: Bug

#115 프론트엔드 요구 사항 구현 및 리팩토링
  src/main/java/com/attica/athens/domain/agora/api/AgoraOpenController.java
  src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
  src/main/java/com/attica/athens/domain/agora/dao/AgoraQueryRepository.java
  src/main/java/com/attica/athens/domain/agora/dao/AgoraQueryRepositoryImpl.java
  src/main/java/com/attica/athens/domain/agora/dto/SimpleClosedAgoraVoteResult.java
  src/main/java/com/attica/athens/domain/agora/dto/request/ClosedAgoraRequest.java
  src/main/java/com/attica/athens/domain/agoraUser/application/AgoraUserService.java
  src/main/java/com/attica/athens/global/auth/application/AuthService.java
  src/main/java/com/attica/athens/global/auth/config/SecurityConfig.java
Labels: 🚩 Priority: High, feature, refactor
