Repository Attica-org/athens-backend, pull requests merged in 2024-07, with the labels that each got.

#121 종료된 아고라에 대한 투표 결과 api 수정
  src/main/java/com/attica/athens/domain/agora/api/AgoraOpenController.java
  src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
  src/main/java/com/attica/athens/domain/agora/dao/AgoraQueryRepository.java
  src/main/java/com/attica/athens/domain/agora/dao/AgoraQueryRepositoryImpl.java
  src/main/java/com/attica/athens/domain/agora/domain/Agora.java
  src/main/java/com/attica/athens/domain/agora/dto/request/AgoraRequest.java
  src/main/java/com/attica/athens/domain/agora/dto/request/SearchCategoryRequest.java
  src/main/resources/application-prod.yml
Labels: 🚩 Priority: High, ✨ Type: Enhancement, refactor

#124 sessionId로 참여자 조회
  src/main/java/com/attica/athens/domain/agora/api/AgoraAuthController.java
  src/main/java/com/attica/athens/domain/agora/api/AgoraOpenController.java
  src/main/java/com/attica/athens/domain/agora/dao/AgoraQueryRepositoryImpl.java
Labels: ✅ Status: Done, refactor

#128 fix: 세션 삭제 문제 해결
  src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
  src/main/java/com/attica/athens/domain/agora/domain/Agora.java
  src/main/java/com/attica/athens/domain/agoraUser/application/AgoraUserService.java
Labels: 🐛 Type: Bug

#129 Dev-> Main
  src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
  src/main/java/com/attica/athens/domain/agora/domain/Agora.java
  src/main/java/com/attica/athens/domain/agoraUser/application/AgoraUserService.java
Labels: 🐛 Type: Bug

#130 참여자 조회 타입 쿼리 수정
  src/main/java/com/attica/athens/domain/agora/dao/AgoraQueryRepositoryImpl.java
Labels: ✅ Status: Done, refactor

#135 fix : 키워드 기반 아고라 리스트 조회 수정
  src/main/java/com/attica/athens/domain/agora/api/AgoraOpenController.java
  src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
  src/main/java/com/attica/athens/domain/agora/dao/AgoraQueryRepository.java
  src/main/java/com/attica/athens/domain/agora/dao/AgoraQueryRepositoryImpl.java
  src/main/resources/application-prod.yml
Labels: 🐛 Type: Bug

#134 Dev -> Main
  src/main/java/com/attica/athens/domain/agora/api/AgoraOpenController.java
  src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
  src/main/java/com/attica/athens/domain/agora/dao/AgoraQueryRepository.java
  src/main/java/com/attica/athens/domain/agora/dao/AgoraQueryRepositoryImpl.java
  src/main/resources/application-prod.yml
Labels: feature

#143 아고라 테스트 추가
  src/main/java/com/attica/athens/domain/agora/dao/AgoraQueryRepositoryImpl.java
  src/main/java/com/attica/athens/domain/agora/domain/Category.java
  src/test/java/com/attica/athens/agora/service/v1/AgoraServiceV1Test.java
  src/test/java/com/attica/athens/config/TestAuditingConfiguration.java
  src/test/java/com/attica/athens/config/TestQueryDslConfig.java
  src/test/java/com/attica/athens/domain/agora/AgoraAuthApiIntegrationTest.java
  src/test/java/com/attica/athens/domain/agora/AgoraOpenApiIntegrationTest.java
  src/test/java/com/attica/athens/domain/agora/dao/AgoraQueryRepositoryImplTest.java
  src/test/java/com/attica/athens/domain/agora/domain/AgoraTest.java
  src/test/resources/sql/get-agora.sql
  src/test/resources/sql/get-base-member.sql
  src/test/resources/sql/get-category.sql
Labels: 🟡 Priority: Medium, ✅ Status: Done, feature, refactor

#147 응답 형식 변경 및 테스트 코드 수정
  src/main/java/com/attica/athens/domain/common/advice/ErrorResponse.java
  src/main/java/com/attica/athens/domain/common/advice/GlobalExceptionHandler.java
  src/test/java/com/attica/athens/domain/agora/AgoraAuthApiIntegrationTest.java
  src/test/java/com/attica/athens/domain/agora/AgoraOpenApiIntegrationTest.java
Labels: refactor
