Repository Attica-org/athens-backend, pull requests merged in 2024-05, with the labels that each got.

#3 chore: 프로젝트 환경 설정
  .github/.gitmessage.txt
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/attica/athens/AthensApplication.java
  src/main/resources/application.yml
  src/test/java/com/attica/athens/AthensApplicationTests.java
Labels: 🟡 Priority: Medium, 🆕 Status: Available, 🔛 Status: In Progress

#8 Feat: Spring Security를 활용한 비회원 로그인 구현
  .github/.gitmessage.txt
  .github/pull_request_template.md
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/attica/athens/AthensApplication.java
  src/main/java/com/attica/athens/config/CorsMvcConfig.java
  src/main/java/com/attica/athens/config/SecurityConfig.java
  src/main/java/com/attica/athens/security/CustomUserDetails.java
  src/main/java/com/attica/athens/security/CustomUserDetailsService.java
  src/main/java/com/attica/athens/security/JWTFilter.java
  src/main/java/com/attica/athens/security/JWTUtil.java
  src/main/java/com/attica/athens/security/LoginFilter.java
  src/main/java/com/attica/athens/user/controller/TempUserController.java
  src/main/java/com/attica/athens/user/controller/TestController.java
  src/main/java/com/attica/athens/user/controller/UserController.java
  src/main/java/com/attica/athens/user/domain/BaseUser.java
  src/main/java/com/attica/athens/user/domain/TempUser.java
  src/main/java/com/attica/athens/user/domain/User.java
  src/main/java/com/attica/athens/user/domain/UserRole.java
  src/main/java/com/attica/athens/user/dto/CreateUserRequest.java
  src/main/java/com/attica/athens/user/repository/TempUserRepository.java
  src/main/java/com/attica/athens/user/repository/UserRepository.java
  src/main/java/com/attica/athens/user/service/TempUserService.java
  src/main/java/com/attica/athens/user/service/UserService.java
  src/main/resources/application.yml
  src/test/java/com/attica/athens/AthensApplicationTests.java
Labels: 🚩 Priority: High, 🔛 Status: In Progress, 🐛 Type: Bug, ✨ Type: Enhancement

#26 feat: 아고리 생성 API 추가
  src/main/java/com/attica/athens/agora/controller/v1/AgoraControllerV1.java
  src/main/java/com/attica/athens/agora/domain/Agora.java
  src/main/java/com/attica/athens/agora/domain/Category.java
  src/main/java/com/attica/athens/agora/dto/AgoraResponse.java
  src/main/java/com/attica/athens/agora/dto/CreateAgoraRequestDto.java
  src/main/java/com/attica/athens/agora/dto/CreateAgoraResponseDto.java
  src/main/java/com/attica/athens/agora/repository/CategoryQueryRepository.java
  src/main/java/com/attica/athens/agora/repository/CategoryQueryRepositoryImpl.java
  src/main/java/com/attica/athens/agora/repository/CategoryRepository.java
  src/main/java/com/attica/athens/agora/service/v1/AgoraServiceV1.java
  src/main/java/com/attica/athens/config/QueryDslConfig.java
  src/test/java/com/attica/athens/agora/service/v1/AgoraServiceV1Test.java
Labels: 🔥 Priority: Urgent, 🆕 Status: Available

#36 feat: cd script 추가
  .github/workflows/backend-cd.yaml
  .github/workflows/backend-ci.yaml
  .gitignore
  Dockerfile
  docker-compose.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: ✅ Status: Done, chore

#37 WebSocket을 이용한 실시간 채팅 기능 구현
  .gitignore
  build.gradle
  src/main/java/com/attica/athens/domain/agoraUser/dao/AgoraUserRepository.java
  src/main/java/com/attica/athens/domain/chat/api/ChatController.java
  src/main/java/com/attica/athens/domain/chat/application/ChatCommandService.java
  src/main/java/com/attica/athens/domain/chat/application/ChatQueryService.java
  src/main/java/com/attica/athens/domain/chat/dao/ChatRepository.java
  src/main/java/com/attica/athens/domain/chat/domain/Chat.java
  src/main/java/com/attica/athens/domain/chat/domain/ChatType.java
  src/main/java/com/attica/athens/domain/chat/dto/request/SendChatRequest.java
  src/main/java/com/attica/athens/domain/chat/dto/response/SendChatResponse.java
  src/main/java/com/attica/athens/domain/user/api/TempUserController.java
  src/main/java/com/attica/athens/domain/user/dao/BaseUserRepository.java
  src/main/java/com/attica/athens/domain/user/dao/TempUserRepository.java
  src/main/java/com/attica/athens/domain/user/dao/UserRepository.java
  src/main/java/com/attica/athens/global/config/JpaConfig.java
  src/main/java/com/attica/athens/global/config/SecurityConfig.java
  src/main/java/com/attica/athens/global/config/WebSocketConfig.java
  src/main/java/com/attica/athens/global/handler/WebSocketEventHandler.java
  src/main/java/com/attica/athens/global/interceptor/JwtChannelInterceptor.java
  src/main/java/com/attica/athens/global/security/JWTFilter.java
  src/main/java/com/attica/athens/global/security/JWTUtil.java
  src/main/java/com/attica/athens/global/security/LoginFilter.java
  src/main/java/com/attica/athens/global/utils/WebSocketUtils.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: 🟡 Priority: Medium, 🔛 Status: In Progress, feature

#44 dev -> main
  src/main/resources/application.yml
Labels: ✅ Status: Done

#48 채팅 api 개발 및 Spring Security에 websocket 인증 통합
  build.gradle
  src/main/java/com/attica/athens/domain/agoraUser/dao/AgoraUserRepository.java
  src/main/java/com/attica/athens/domain/agoraUser/domain/AgoraUser.java
  src/main/java/com/attica/athens/domain/chat/api/ChatController.java
  src/main/java/com/attica/athens/domain/chat/application/ChatCommandService.java
  src/main/java/com/attica/athens/domain/chat/application/ChatQueryService.java
  src/main/java/com/attica/athens/domain/chat/dao/ChatRepository.java
  src/main/java/com/attica/athens/domain/chat/domain/Chat.java
  src/main/java/com/attica/athens/domain/chat/domain/ChatType.java
  src/main/java/com/attica/athens/domain/chat/dto/Cursor.java
  src/main/java/com/attica/athens/domain/chat/dto/response/GetChatParticipants.java
  src/main/java/com/attica/athens/domain/chat/dto/response/GetChatResponse.java
  src/main/java/com/attica/athens/domain/chat/dto/response/SendChatResponse.java
  src/main/java/com/attica/athens/domain/chat/dto/response/SendMetaResponse.java
  src/main/java/com/attica/athens/domain/user/application/TempUserService.java
  src/main/java/com/attica/athens/domain/user/domain/User.java
  src/main/java/com/attica/athens/global/config/JpaConfig.java
  src/main/java/com/attica/athens/global/config/SecurityConfig.java
  src/main/java/com/attica/athens/global/config/WebSocketConfig.java
  src/main/java/com/attica/athens/global/config/WebSocketSecurityConfig.java
  src/main/java/com/attica/athens/global/handler/WebSocketEventHandler.java
  src/main/java/com/attica/athens/global/interceptor/JwtChannelInterceptor.java
  src/main/java/com/attica/athens/global/security/CustomUserDetails.java
  src/main/java/com/attica/athens/global/security/CustomUserDetailsService.java
  src/main/java/com/attica/athens/global/security/JWTFilter.java
  src/main/java/com/attica/athens/global/security/JWTUtil.java
  src/main/java/com/attica/athens/global/security/LoginFilter.java
  src/main/resources/application-prod.yml
Labels: 🚩 Priority: High, 🔛 Status: In Progress, feature

#51 Refresh/Access Token 재발급 및 Logout Filter 구현
  src/main/java/com/attica/athens/domain/chat/api/ChatController.java
  src/main/java/com/attica/athens/domain/chat/application/ChatCommandService.java
  src/main/java/com/attica/athens/domain/common/advice/GlobalExceptionHandler.java
  src/main/java/com/attica/athens/domain/user/api/TempUserController.java
  src/main/java/com/attica/athens/domain/user/application/TempUserService.java
  src/main/java/com/attica/athens/global/config/JpaConfig.java
  src/main/java/com/attica/athens/global/config/SecurityConfig.java
  src/main/java/com/attica/athens/global/interceptor/JwtChannelInterceptor.java
  src/main/java/com/attica/athens/global/security/filter/CustomLogoutFilter.java
  src/main/java/com/attica/athens/global/security/filter/LoginFilter.java
  src/main/java/com/attica/athens/global/security/jwt/JWTFilter.java
  src/main/java/com/attica/athens/global/security/jwt/JWTUtil.java
  src/main/java/com/attica/athens/global/security/refresh/api/ReissueController.java
  src/main/java/com/attica/athens/global/security/refresh/application/ReissueService.java
  src/main/java/com/attica/athens/global/security/refresh/dao/RefreshRepository.java
  src/main/java/com/attica/athens/global/security/refresh/domain/RefreshToken.java
  src/main/java/com/attica/athens/global/security/refresh/dto/CreateCookieResponse.java
  src/main/java/com/attica/athens/global/security/refresh/dto/CreateRefreshTokenRequest.java
  src/main/java/com/attica/athens/global/security/userdetail/CustomUserDetails.java
  src/main/java/com/attica/athens/global/security/userdetail/CustomUserDetailsService.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/com/attica/athens/agora/service/v1/AgoraServiceV1Test.java
Labels: 🟡 Priority: Medium, 🔛 Status: In Progress, feature

#55 인증/인가 로직과 security 패키지 분리
  build.gradle
  config/checkstyle/google-checkstyle.xml
  config/checkstyle/intellij-java-wooteco-style.xml
  src/main/java/com/attica/athens/domain/agora/api/AgoraController.java
  src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
  src/main/java/com/attica/athens/domain/agora/dao/AgoraQueryRepository.java
  src/main/java/com/attica/athens/domain/agora/dao/AgoraQueryRepositoryImpl.java
  src/main/java/com/attica/athens/domain/agora/domain/Agora.java
  src/main/java/com/attica/athens/domain/agora/domain/AgoraStatus.java
  src/main/java/com/attica/athens/domain/agora/dto/SimpleAgoraResult.java
  src/main/java/com/attica/athens/domain/agora/dto/SimpleParticipants.java
  src/main/java/com/attica/athens/domain/agora/dto/request/SearchCategoryRequest.java
  src/main/java/com/attica/athens/domain/agora/dto/request/SearchKeywordRequest.java
  src/main/java/com/attica/athens/domain/agora/exception/NotFoundCategoryException.java
  src/main/java/com/attica/athens/domain/chat/api/ChatController.java
  src/main/java/com/attica/athens/domain/chat/application/ChatCommandService.java
  src/main/java/com/attica/athens/domain/common/advice/ErrorCode.java
  src/main/java/com/attica/athens/domain/common/advice/GlobalExceptionHandler.java
  src/main/java/com/attica/athens/domain/user/api/TempUserController.java
  src/main/java/com/attica/athens/domain/user/application/TempUserService.java
  src/main/java/com/attica/athens/domain/user/dao/UserRepository.java
  src/main/java/com/attica/athens/global/auth/CustomUserDetails.java
  src/main/java/com/attica/athens/global/auth/CustomUserDetailsService.java
  src/main/java/com/attica/athens/global/auth/api/ReissueController.java
  src/main/java/com/attica/athens/global/auth/application/AuthService.java
  src/main/java/com/attica/athens/global/auth/config/SecurityConfig.java
  src/main/java/com/attica/athens/global/auth/dao/RefreshTokenRepository.java
  src/main/java/com/attica/athens/global/auth/domain/RefreshToken.java
  src/main/java/com/attica/athens/global/auth/dto/request/CreateRefreshTokenRequest.java
  src/main/java/com/attica/athens/global/auth/dto/response/CreateAccessTokenResponse.java
  src/main/java/com/attica/athens/global/auth/exception/InvalidAuthorizationHeaderException.java
  src/main/java/com/attica/athens/global/auth/exception/JwtExpiredException.java
  src/main/java/com/attica/athens/global/auth/exception/JwtIllegalArgumentException.java
  src/main/java/com/attica/athens/global/auth/exception/JwtSignatureException.java
  src/main/java/com/attica/athens/global/auth/exception/JwtUnsupportedJwtException.java
  src/main/java/com/attica/athens/global/auth/exception/NotFoundRefreshTokenException.java
  src/main/java/com/attica/athens/global/auth/filter/CustomLogoutFilter.java
  src/main/java/com/attica/athens/global/auth/filter/JwtAuthenticationEntryPoint.java
  src/main/java/com/attica/athens/global/auth/filter/JwtFilter.java
  src/main/java/com/attica/athens/global/auth/filter/LoginFilter.java
  src/main/java/com/attica/athens/global/auth/jwt/Constants.java
  src/main/java/com/attica/athens/global/auth/jwt/JwtUtils.java
  src/main/java/com/attica/athens/global/config/JpaConfig.java
  src/main/java/com/attica/athens/global/interceptor/JwtChannelInterceptor.java
  src/main/java/com/attica/athens/global/security/jwt/JWTFilter.java
  src/main/java/com/attica/athens/global/security/jwt/JWTUtil.java
  src/main/java/com/attica/athens/global/security/refresh/api/ReissueController.java
  src/main/java/com/attica/athens/global/security/refresh/application/ReissueService.java
  src/main/java/com/attica/athens/global/security/refresh/dto/CreateCookieResponse.java
  src/main/java/com/attica/athens/global/security/refresh/dto/CreateRefreshTokenRequest.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/com/attica/athens/AthensApplicationTests.java
  src/test/java/com/attica/athens/agora/service/v1/AgoraServiceV1Test.java
  src/test/java/com/attica/athens/global/auth/JwtUtilsTest.java
Labels: 🟡 Priority: Medium, 🔛 Status: In Progress, ✨ Type: Enhancement, refactor
