Repository Attica-org/athens-backend, pull requests merged in 2024-11, with the labels that each got.

#240 세션, 아고라멤버 오류 해결
  src/main/java/com/attica/athens/domain/agoraMember/application/AgoraMemberService.java
  src/main/java/com/attica/athens/domain/chat/api/ChatAuthController.java
  src/main/java/com/attica/athens/domain/common/AuditingFields.java
  src/main/java/com/attica/athens/domain/member/api/MemberAuthController.java
  src/main/java/com/attica/athens/domain/member/application/MemberService.java
  src/main/java/com/attica/athens/domain/member/dao/MemberRepository.java
  src/main/java/com/attica/athens/domain/member/dto/response/GetMemberResponse.java
  src/main/java/com/attica/athens/domain/member/exception/AlreadyActivateMemberException.java
  src/main/java/com/attica/athens/domain/member/exception/UnauthorizedException.java
  src/main/java/com/attica/athens/domain/member/scheduler/MemberDeletionScheduler.java
  src/main/java/com/attica/athens/global/handler/HeartBeatHandler.java
  src/main/java/com/attica/athens/global/handler/WebSocketEventHandler.java
Labels: 🐛 Type: Bug

#241 Dev -> Main
  src/main/java/com/attica/athens/domain/agoraMember/application/AgoraMemberService.java
  src/main/java/com/attica/athens/domain/chat/api/ChatAuthController.java
  src/main/java/com/attica/athens/domain/common/AuditingFields.java
  src/main/java/com/attica/athens/domain/member/api/MemberAuthController.java
  src/main/java/com/attica/athens/domain/member/api/MemberOpenController.java
  src/main/java/com/attica/athens/domain/member/application/MemberService.java
  src/main/java/com/attica/athens/domain/member/application/TempMemberService.java
  src/main/java/com/attica/athens/domain/member/dao/MemberRepository.java
  src/main/java/com/attica/athens/domain/member/domain/TokenType.java
  src/main/java/com/attica/athens/domain/member/dto/response/GetMemberResponse.java
  src/main/java/com/attica/athens/domain/member/exception/AlreadyActivateMemberException.java
  src/main/java/com/attica/athens/domain/member/exception/UnauthorizedException.java
  src/main/java/com/attica/athens/domain/member/scheduler/MemberDeletionScheduler.java
  src/main/java/com/attica/athens/global/auth/application/AuthService.java
  src/main/java/com/attica/athens/global/auth/config/SecurityConfig.java
  src/main/java/com/attica/athens/global/auth/config/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/attica/athens/global/auth/dao/RefreshTokenRepository.java
  src/main/java/com/attica/athens/global/auth/exception/BlacklistedTokenException.java
  src/main/java/com/attica/athens/global/auth/filter/CustomLogoutFilter.java
  src/main/java/com/attica/athens/global/auth/filter/JwtFilter.java
  src/main/java/com/attica/athens/global/auth/filter/LoginFilter.java
  src/main/java/com/attica/athens/global/auth/jwt/Constants.java
  src/main/java/com/attica/athens/global/auth/jwt/JwtUtils.java
  src/main/java/com/attica/athens/global/auth/scheduler/TokenCleanupScheduler.java
  src/main/java/com/attica/athens/global/handler/HeartBeatHandler.java
  src/main/java/com/attica/athens/global/handler/WebSocketEventHandler.java
  src/main/java/com/attica/athens/global/interceptor/JwtChannelInterceptor.java
  src/main/resources/application-prod.yml
  src/test/java/com/attica/athens/domain/token/RefreshTokenApiIntegrationTest.java
  src/test/java/com/attica/athens/global/auth/JwtUtilsTest.java
  src/test/java/com/attica/athens/support/WebSocketIntegrationTestSupport.java
Labels: 🐛 Type: Bug

#238 아고라 유저 추방 투표 API 추가
  src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
  src/main/java/com/attica/athens/domain/agora/domain/Agora.java
  src/main/java/com/attica/athens/domain/agora/vote/api/AgoraVoteController.java
  src/main/java/com/attica/athens/domain/agora/vote/application/AgoraVoteService.java
  src/main/java/com/attica/athens/domain/agora/vote/domain/KickVote.java
  src/main/java/com/attica/athens/domain/agora/vote/dto/request/KickVoteRequest.java
  src/main/java/com/attica/athens/domain/agora/vote/dto/response/KickVoteResult.java
  src/main/java/com/attica/athens/domain/agora/vote/dto/response/SendKickResponse.java
  src/main/java/com/attica/athens/domain/agora/vote/exception/AlreadyKickVotedException.java
  src/main/java/com/attica/athens/domain/agoraMember/dto/response/SendMetaResponse.java
  src/main/java/com/attica/athens/domain/chat/domain/ChatType.java
  src/test/java/com/attica/athens/domain/vote/AgoraVoteAuthApiIntegrationTest.java
  src/test/java/com/attica/athens/domain/vote/AgoraVoteWebSocketApiIntegerationTest.java
  src/test/java/com/attica/athens/domain/vote/domain/KickVoteTest.java
  src/test/resources/sql/get-agora.sql
  src/test/resources/sql/get-base-member.sql
Labels: 🟡 Priority: Medium, 🔛 Status: In Progress, ✨ Type: Enhancement, feature

#242 kakao 로그인시 이메일 조회되도록 수정
  src/main/java/com/attica/athens/domain/member/domain/Member.java
  src/main/java/com/attica/athens/domain/member/dto/response/GetMemberResponse.java
  src/main/java/com/attica/athens/global/auth/config/oauth2/member/GoogleOAuth2MemberInfo.java
  src/main/java/com/attica/athens/global/auth/config/oauth2/member/KakaoOAuth2MemberInfo.java
  src/main/java/com/attica/athens/global/auth/config/oauth2/member/OAuth2MemberInfo.java
  src/main/resources/application-prod.yml
  src/test/java/com/attica/athens/domain/member/MemberAuthApiIntegrationTest.java
  src/test/java/com/attica/athens/domain/member/domain/MemberTest.java
Labels: feature

#244 아고라 재입장 검증 수정
  src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
Labels: 🟡 Priority: Medium, ✅ Status: Done, refactor

#245 프론트 요구사항 (Bug Fix)
  build.gradle
  src/main/java/com/attica/athens/domain/agora/api/AgoraAuthController.java
  src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
  src/main/java/com/attica/athens/domain/agoraMember/application/AgoraMemberService.java
  src/main/java/com/attica/athens/domain/agoraMember/dao/AgoraMemberRepository.java
  src/main/java/com/attica/athens/domain/member/api/MemberAuthController.java
  src/main/java/com/attica/athens/domain/member/application/MemberService.java
  src/main/java/com/attica/athens/domain/member/dto/response/DeleteMemberResponse.java
  src/main/java/com/attica/athens/domain/member/exception/UnauthorizedException.java
  src/main/java/com/attica/athens/global/auth/config/SecurityConfig.java
  src/main/java/com/attica/athens/global/handler/HeartBeatHandler.java
Labels: 🚩 Priority: High, refactor
