Repository Attica-org/athens-backend, pull requests merged in 2024-09, with the labels that each got.

#164 채팅 반응하기 기능 구현
  src/main/java/com/attica/athens/domain/chat/api/ChatAuthController.java
  src/main/java/com/attica/athens/domain/chat/application/ChatCommandService.java
  src/main/java/com/attica/athens/domain/chat/dao/ReactionRepository.java
  src/main/java/com/attica/athens/domain/chat/domain/ChatType.java
  src/main/java/com/attica/athens/domain/chat/domain/Reaction.java
  src/main/java/com/attica/athens/domain/chat/domain/ReactionType.java
  src/main/java/com/attica/athens/domain/chat/dto/projection/ReactionCount.java
  src/main/java/com/attica/athens/domain/chat/dto/request/SendReactionRequest.java
  src/main/java/com/attica/athens/domain/chat/dto/response/SendReactionResponse.java
  src/main/java/com/attica/athens/domain/chat/exception/NotFoundChatException.java
  src/main/java/com/attica/athens/domain/chat/exception/WriterReactionException.java
  src/main/java/com/attica/athens/global/handler/WebSocketExceptionHandler.java
  src/test/java/com/attica/athens/domain/chat/ChatWebSocketApiIntegrationTest.java
  src/test/resources/sql/send-valid-reaction.sql
Labels: feature, test

#170 thumbnail 도메인 추가
  src/main/java/com/attica/athens/domain/agora/dao/AgoraThumbnailRepository.java
  src/main/java/com/attica/athens/domain/agora/domain/AgoraThumbnail.java
Labels: 🟡 Priority: Medium, 🔛 Status: In Progress, ✨ Type: Enhancement, feature

#179 [#]refactor: 비속어 api get을 post로 변경
  src/main/java/com/attica/athens/domain/chat/api/ChatAuthController.java
Labels: refactor

#181 로그 수정 및 deploy-prod.sh 수정
  deploy-prod.sh
  src/main/java/com/attica/athens/global/handler/WebSocketEventHandler.java
Labels: refactor

#185 세션 관련 문제 수정
  src/main/generated/com/attica/athens/domain/agora/domain/QAgora.java
  src/main/generated/com/attica/athens/domain/agora/domain/QCategory.java
  src/main/generated/com/attica/athens/domain/agora/domain/QTrend.java
  src/main/generated/com/attica/athens/domain/chat/domain/QChat.java
  src/main/generated/com/attica/athens/domain/chat/domain/QChatContent.java
  src/main/generated/com/attica/athens/domain/chat/domain/QReaction.java
  src/main/generated/com/attica/athens/domain/common/QAuditingFields.java
  src/main/generated/com/attica/athens/domain/member/domain/QBaseMember.java
  src/main/generated/com/attica/athens/domain/member/domain/QMember.java
  src/main/generated/com/attica/athens/domain/member/domain/QTempMember.java
  src/main/generated/com/attica/athens/global/auth/domain/QRefreshToken.java
  src/main/java/com/attica/athens/global/handler/WebSocketEventHandler.java
Labels: 🐛 Type: Bug, refactor

#171 아고라 생성 API 리팩토링 및 프로필 이미지 수정 API 추가
  build.gradle
  deploy-prod.sh
  src/main/java/com/attica/athens/domain/agora/api/AgoraAuthController.java
  src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
  src/main/java/com/attica/athens/domain/agora/application/S3ThumbnailService.java
  src/main/java/com/attica/athens/domain/agora/dao/AgoraQueryRepositoryImpl.java
  src/main/java/com/attica/athens/domain/agora/dao/AgoraThumbnailRepository.java
  src/main/java/com/attica/athens/domain/agora/domain/Agora.java
  src/main/java/com/attica/athens/domain/agora/domain/AgoraThumbnail.java
  src/main/java/com/attica/athens/domain/agora/dto/SimpleAgoraResult.java
  src/main/java/com/attica/athens/domain/agora/dto/SimpleClosedAgoraVoteResult.java
  src/main/java/com/attica/athens/global/config/S3Config.java
  src/main/resources/application-prod.yml
  src/test/java/com/attica/athens/domain/agora/AgoraAuthApiIntegrationTest.java
  src/test/java/com/attica/athens/domain/agora/dao/AgoraQueryRepositoryImplTest.java
Labels: 🟡 Priority: Medium, 🔛 Status: In Progress, feature, refactor

#186 Dev -> Main
  build.gradle
  deploy-prod.sh
  src/main/generated/com/attica/athens/domain/agora/domain/QAgora.java
  src/main/generated/com/attica/athens/domain/agora/domain/QCategory.java
  src/main/generated/com/attica/athens/domain/agora/domain/QTrend.java
  src/main/generated/com/attica/athens/domain/chat/domain/QChat.java
  src/main/generated/com/attica/athens/domain/chat/domain/QChatContent.java
  src/main/generated/com/attica/athens/domain/chat/domain/QReaction.java
  src/main/generated/com/attica/athens/domain/common/QAuditingFields.java
  src/main/generated/com/attica/athens/domain/member/domain/QBaseMember.java
  src/main/generated/com/attica/athens/domain/member/domain/QMember.java
  src/main/generated/com/attica/athens/domain/member/domain/QTempMember.java
  src/main/generated/com/attica/athens/global/auth/domain/QRefreshToken.java
  src/main/java/com/attica/athens/domain/agora/api/AgoraAuthController.java
  src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
  src/main/java/com/attica/athens/domain/agora/application/S3ThumbnailService.java
  src/main/java/com/attica/athens/domain/agora/dao/AgoraQueryRepositoryImpl.java
  src/main/java/com/attica/athens/domain/agora/dao/AgoraThumbnailRepository.java
  src/main/java/com/attica/athens/domain/agora/domain/Agora.java
  src/main/java/com/attica/athens/domain/agora/domain/AgoraThumbnail.java
  src/main/java/com/attica/athens/domain/agora/dto/SimpleAgoraResult.java
  src/main/java/com/attica/athens/domain/agora/dto/SimpleClosedAgoraVoteResult.java
  src/main/java/com/attica/athens/global/config/S3Config.java
  src/main/java/com/attica/athens/global/handler/WebSocketEventHandler.java
  src/main/resources/application-prod.yml
  src/test/java/com/attica/athens/domain/agora/AgoraAuthApiIntegrationTest.java
  src/test/java/com/attica/athens/domain/agora/dao/AgoraQueryRepositoryImplTest.java
Labels: refactor

#188 소켓 메타데이터 응답 수정
  src/main/java/com/attica/athens/global/handler/WebSocketEventHandler.java
Labels: refactor
